schema_version = "1.0.0"

id = "ray34g.save_versions_redirector"
version = "1.2.0"
name = "Save Versions Redirector"
tagline = "Manage backup save versions automatically"
maintainer = "ray34g <Go.Ray@ray34g.com>"
type = "add-on"

description = """
Keeps a rolling set of backups: 'latest', 'prev1', 'prev2' … .
Each slot has its own minimum‑age threshold before being overwritten.
"""

license = [
  "SPDX:MIT"
]

blender_version_min = "4.2.0"

# website = "https://github.com/ray34g/save_versions_redirector"
platforms = ["windows-x64", "macos-x64", "linux-x64"]
tags = ["System", "Files", "Automation"]
